- name: Set locale
  become: yes
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Set timezone
  become: yes
  timezone:
    name: Asia/Tokyo

- name: Create SSH directory
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Copy SSH key
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: ~/.ssh/authorized_keys
    mode: 0600

- name: Configure SSH settings
  become: yes
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      PermitRootLogin no
      PubkeyAuthentication yes
      PasswordAuthentication no

- name: Restart sshd
  become: yes
  service:
    name: sshd
    state: restarted

- name: Create Smarthome API directory
  become: yes
  file:
    path: /var/www/smarthome-api
    state: directory
    owner: pi

- name: Create Smarthome API shared directory
  become: yes
  file:
    path: /var/www/smarthome-api/shared
    state: directory
    owner: pi

- name: Create Smarthome API shared config directory
  become: yes
  file:
    path: /var/www/smarthome-api/shared/config
    state: directory
    owner: pi

- name: Copy Rails secret key
  template:
    src: roles/settings/templates/master.key.j2
    dest: /var/www/smarthome-api/shared/config/master.key

- name: Create Smarthome API shared SSL directory
  become: yes
  file:
    path: /var/www/smarthome-api/shared/ssl
    state: directory
    owner: pi

- name: Copy SSL server certificate
  template:
    src: roles/settings/templates/server.crt.j2
    dest: /var/www/smarthome-api/shared/ssl/server.crt

- name: Copy SSL secret key
  template:
    src: roles/settings/templates/server.key.j2
    dest: /var/www/smarthome-api/shared/ssl/server.key
